import numpy as np
import gp_patch.deap_fix as deap_fix
from gp_tools.tree_runner import run_tree
from deap.gp import PrimitiveTree
from gp_terminals.gp_image import GPImage


def sigmoid_activation(x):
    # To avoid overflow
    x = np.clip(x, -10, 10)

    return 1/(1 + np.exp(-x))


class GPTree:
    """
    Class that represent tree generated by GP.
    Can execute itself.
    """
    def __init__(self, pset, min_depth: int = 2, max_depth: int = 10, tree: PrimitiveTree = None) -> None:
        """
        Create a new tree.
        
        Parameter
        ---------
        pset: PrimitiveTypedSet
            Primitive set to generate a tree.
        min_depth: int
            Minimum depth of the tree.
        max_depth: int
            Maximum depth of the tree.
        tree: PrimitiveTree
            If specified then create class based on created tree.

        """
        self.pset = pset
        self.score = 0
        if tree is None:
            expr = deap_fix.genFull(pset, min_=min_depth, max_=max_depth)
            self.tree = PrimitiveTree(expr)
        else:
            self.tree = tree
        
    def predict(self, image: GPImage) -> np.float64:
        """
        Predict class based on argument.

        Parameter
        ---------
        image: GPImage
            Image for class prediction.
        
        Returns
        -------
        np.float64: Result of prediction.
        """
        x = run_tree(image, self.tree)
        return sigmoid_activation(x)