import numpy as np
import gp_patch.deap_fix as deap_fix
from tools.tree_runner import run_tree
from deap import gp
from gp_terminals.gp_image import GPImage


def sigmoid_activation(x):
    # To avoid overflow
    x = np.clip(x, -10, 10)
    
    return 1/(1 + np.exp(-x))


class GPTree:
    """
    Class that represent tree generated by GP.
    Can execute itself.
    """
    def __init__(self, pset, min_depth: int = 2, max_depth: int = 10, tree: gp.PrimitiveTree = None) -> None:
        """
        Create a new tree.

        """
        self.pset = pset
        if tree is None:
            expr = deap_fix.genFull(pset, min_=min_depth, max_=max_depth)
            self.tree = gp.PrimitiveTree(expr)
        else:
            self.tree = tree
        
    def predict(self, image: GPImage) -> np.float64:
        """
        Predict class based on argument.
        """
        x = run_tree(image, self.tree)
        return sigmoid_activation(x)